# Generated by Django 3.1.3 on 2021-10-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=8)),
                ('description', models.TextField(max_length=5000)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
